name: CMake Build

on:
  push:
    branches: [ master, main ]
  schedule:
    - cron: '0 2 * * *'  # Nightly at 2 AM

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libglfw3-dev libgl1-mesa-dev libglm-dev libcjson-dev

    - name: Build and Install CVector
      run: |
        git clone http://192.168.1.122:3001/ProgrammingCube/c_vector.git
        cd c_vector
        mkdir build && cd build
        cmake ..
        make
        sudo make install
        cd ../..
    
    - name: Build
      run: |
        mkdir build && cd build
        cmake ..
        make
    
    - name: Run Tests
      run: |
        cd build/tests
        ./tropic_test